name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.0  # Using stable release
        with:
          host: ${{ secrets.HOST_DNS }}
          username: omkar  # Replace with the username you wish to use
          password: ${{ secrets.EC2_USER_PASSWORD }}
          script: |
            rsync -avz --delete ./ "${{ secrets.TARGET_DIR }}/"
