name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/ec2_key
          chmod 600 /tmp/ec2_key
          scp -o StrictHostKeyChecking=no -i /tmp/ec2_key -r * ec2-user@34.207.234.166:/home/ec2-user/vizipp
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key ec2-user@34.207.234.166 'cd /home/ec2-user/vizipp && ./deploy.sh'
